#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
git lfs pre-push "$@"

# Uncomment next line for DEBUG
#set -x

echo "Running static analysis..."

pwd

# Validate Kotlin code with detekt
./gradlew -q detekt ktlintCheck --no-daemon

status=$?

if [[ "$status" = 0 ]] ; then
    echo "Static analysis found no issues. Proceeding with push."
    exit 0
else
    echo 1>&2 "Static analysis found issues you need to fix before pushing."
    exit 1
fi