coverage:
    precision: 2
    round: down
    range: "70...100"

comment:
    layout: "diff,files"
    behavior: default
    require_changes: no

# Validate:
#   curl --data-binary @.codecov.yml https://codecov.io/validate