/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.klarna.gradle.reactnative

import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'com.klarna.gradle.reactnative.greeting' plugin.
 */
class GradleReactNativePluginFunctionalTest {
    @Test
    fun `can run task`() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id('com.klarna.gradle.reactnative.greeting')
            }
        """.trimIndent())

        // Run the build
        val result = GradleRunner.create()
                .forwardOutput()
                .withPluginClasspath()
                .withProjectDir(projectDir)
                .withArguments("greeting")
                .build();

        // Verify the result
        assertTrue(result.output.contains("Hello from plugin 'com.klarna.gradle.reactnative.greeting'"))
    }

    @Test
    fun `can configure extension`() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id('com.klarna.gradle.reactnative.greeting')
            }
            react {
               root "../.."
               bundleAssetName "index.android.bundle"
               entryFile "index.android.js"
            }
        """.trimIndent())

        // Run the build
        val result = GradleRunner.create()
                .forwardOutput()
                .withPluginClasspath()
                .withProjectDir(projectDir)
                .withArguments("greeting")
                .build();

        // Verify the result
        assertTrue(result.output.contains("Hello from plugin 'com.klarna.gradle.reactnative.greeting'"))

    }
}
