/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.klarna.gradle.reactnative

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.klarna.gradle.reactnative.buildJsBundle' plugin.
 */
class GradleReactNativePluginTest {
    @Test
    fun `plugin registers task compileRnBundle`() {
        // Given
        val project = ProjectBuilder.builder().build()

        // When
        project.plugins.apply(GradleReactNativePlugin.PLUGIN)

        // Then
        assertNotNull(project.tasks.findByName(CompileRnBundleTask.NAME))
    }

    @Test
    fun `plugin register task copyJsBundle`() {
        // Given
        val project = ProjectBuilder.builder().build()

        // When
        project.plugins.apply(GradleReactNativePlugin.PLUGIN)

        // Then
        assertNotNull(project.tasks.findByName(CopyRnBundleTask.NAME))
    }

    @Test
    fun `plugin register extension`() {
        // Given
        val project = ProjectBuilder.builder().build()

        // When
        project.plugins.apply(GradleReactNativePlugin.PLUGIN)

        // Then
        val actual: ReactNativeExtension? = project.extensions
            .findByName(GradleReactNativePlugin.EXTENSION) as ReactNativeExtension?

        assertNotNull(actual)
        assertEquals("../../", actual.root)
    }
}
